### ISSUE TITLE
Add support for light/dark modes.

### ISSUE THREAD

**Issue by damymetzke** [damymetzke/yaml-route-doc#67]
Currently the output generated will support a single style.
End users may prefer a light or dark theme.
To achieve this there will be one of 2 classes present at the root of each document: `theme-dark` or `theme-light`.
This value can then be changed using some JavaScript code.

In the resulting CSS something along the following lines is desired:

```css
.theme-light routedoc--index{
  /* content */
}

.theme-light routedoc--route{
  /* content */
}

.theme-dark routedoc--index{
  /* content */
}

.theme-dark routedoc--route{
  /* content */
}
```

The content between dark and light variants should be very similar.
The biggest difference should be that the foreground and background colors are swapped.
In light mode the foreground should be dark and the background light.
In dark mode the opposite should be true.

To achieve this all classes should be defined as a mixin.
This mixin takes variables for the foreground and background colors.
Then the mixin is called twice, once for light mode and once for dark mode.
This should look something like this:

```scss
@mixin generic($foreground, $background) {
  routedoc--card {
    color: map.get($foreground, "text");
  }
}

.theme-light {
  @include generic(vars.$foreground-light, vars.$background-light);
}

```
